name: Deploy Zola site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to 'master' if your default branch uses that name

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Ensures themes installed as submodules are fetched

      - name: Build and deploy
        uses: getzola/github-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

